### ISSUE TITLE
ptr.get is not a function

### ISSUE THREAD

**Issue by Cinaeth** [speedcontrol/nodecg-speedcontrol#122]
Hello,

I am seeing the following errors when starting nodecg and speed control. I have checked the cfg json using an online json checker, but will post it below the errors for just in case I am missing sometihng.

[Replicant/nodecg-speedcontrol.horaroImportSavedOpts] Schema could not be loaded, are you sure that it is valid JSON?
 TypeError: ptr.get is not a function
    at resolvePointerReference (/media/Cinaeth/Games/nodecg/lib/replicant/schema-hacks.js:114:13)
    at replaceRefs (/media/Cinaeth/Games/nodecg/lib/replicant/schema-hacks.js:41:23)
    at replaceRefs (/media/Cinaeth/Games/nodecg/lib/replicant/schema-hacks.js:69:3)
    at replaceRefs (/media/Cinaeth/Games/nodecg/lib/replicant/schema-hacks.js:69:3)
    at replaceRefs (/media/Cinaeth/Games/nodecg/lib/replicant/schema-hacks.js:69:3)
    at replaceRefs (/media/Cinaeth/Games/nodecg/lib/replicant/schema-hacks.js:69:3)
    at replaceRefs (/media/Cinaeth/Games/nodecg/lib/replicant/schema-hacks.js:69:3)
    at replaceRefs (/media/Cinaeth/Games/nodecg/lib/replicant/schema-hacks.js:69:3)
    at new Replicant (/media/Cinaeth/Games/nodecg/lib/replicant/replicant.js:98:20)
    at new NodeCG.Replicant (/media/Cinaeth/Games/nodecg/lib/api.js:455:9)
    at NodeCG.Replicant (/media/Cinaeth/Games/nodecg/lib/api.js:516:9)
    at Object.<anonymous> (/media/Cinaeth/Games/nodecg/bundles/nodecg-speedcontrol/extension/util/replicants.js:11:48)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/media/Cinaeth/Games/nodecg/bundles/nodecg-speedcontrol/extension/twitch-api.js:40:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/media/Cinaeth/Games/nodecg/bundles/nodecg-speedcontrol/extension/ffz-ws.js:39:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/media/Cinaeth/Games/nodecg/bundles/nodecg-speedcontrol/extension/run-control.js:36:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (/media/Cinaeth/Games/nodecg/bundles/nodecg-speedcontrol/extension/index.js:11:5)
    at _loadExtension (/media/Cinaeth/Games/nodecg/lib/server/extensions.js:103:37)
    at EventEmitter.module.exports.init (/media/Cinaeth/Games/nodecg/lib/server/extensions.js:32:6)
    at EventEmitter.module.exports.start (/media/Cinaeth/Games/nodecg/lib/server/index.js:310:19)
    at Object.<anonymous> (/media/Cinaeth/Games/nodecg/index.js:77:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Command.<anonymous> (/usr/local/lib/node_modules/nodecg-cli/dist/commands/start.js:11:13)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/nodecg-cli/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/usr/local/lib/node_modules/nodecg-cli/node_modules/commander/index.js:1002:14)
    at Command._dispatchSubcommand (/usr/local/lib/node_modules/nodecg-cli/node_modules/commander/index.js:953:18)
    at Command._parseCommand (/usr/local/lib/node_modules/nodecg-cli/node_modules/commander/index.js:970:12)
    at Command.parse (/usr/local/lib/node_modules/nodecg-cli/node_modules/commander/index.js:801:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodecg-cli/dist/index.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodecg-cli/dist/bin/nodecg.js:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
---------------------------------------------------------------------------------------------------------------------------------------------
{
  "language": "en",
  "twitch": {
    "enabled": true,
    "clientID": "xxx",
    "clientSecret": "xxx",
    "redirectURI": "https://dashboard.green-gaming.org/nodecg-speedcontrol/twitchauth",
    "streamTitle": "Green Gaming Fest 2022 benefiting One Tree Planted | {{game}} - {{category}} - by: {{players}}",
    "streamDefaultGame": "Games + Demos",
    "ffzIntegration": false
  },
  "horaro": {
    "defaultURL": " ",
    "disableSpeedrunComLookup": false
  },
  "oengus": {
    "defaultMarathon": "SHORTNAME",
    "useJapanese": false,
    "disableSpeedrunComLookup": false
  },
  "customData": {
    "run": [
      {
        "name": "Host",
        "key": "host",
        "ignoreMarkdown": false
      },
      {
        "name": "1st Couch",
        "key": "couch1",
        "ignoreMarkdown": false
      },
      {
        "name": "2nd Couch",
        "key": "couch2",
        "ignoreMarkdown": false
      },
      {
        "name": "3rd Couch",
        "key": "couch3",
        "ignoreMarkdown": false
      },
      {
        "name": "Layout",
        "key": "layout",
        "ignoreMarkdown": false
      }
    ]
  }
}

**Comment by zoton2** [comment]
This is actually referring to the JSON structure of a replicant we save internally, I forget what the issue is but I also saw it myself recently, but unfortunately I forgot the fix. I think as it's internal to NodeCG I might've done a reinstall of NodeCG using `nodecg-cli`? Because it happened after I tried to update them manually.
